# Series df[series]

## 3. Pandas Series: Math Operation

In [1]:
import pandas as pd
import seaborn as sns

# Load Titanic dataset
df = sns.load_dataset('titanic')

In [2]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [3]:
df['age'].add(10).head()  # Adds 10 to each age

0    32.0
1    48.0
2    36.0
3    45.0
4    45.0
Name: age, dtype: float64

___

In [5]:
import pandas as pd
import numpy as np
from onedrive_loader import files, load

In [6]:
files()

['financial_transactions_dataset_analytics_kaggle',
 'powerbI_data_lakehouse',
 'region_electric_hourly_time_series',
 'sundry_data_sources']

In [7]:
files('sundry_data_sources')

['22025_qs_world_university_rankings.csv',
 'adidas_us_sales_datasets.xlsx',
 'apple_amazon_google_microsoft_daily_stock_returns_10years.xlsx',
 'country_economy_indicator_1950_2022.xlsx',
 'country_gdp_per_capital_1952_2007.xlsx',
 'end_of_month_retail_inventories_and_inventories1992_2024.xlsx',
 'financial_sample_data.xlsx',
 'job_roles_opening_analyst.xlsx',
 'monthly_retail_and_food_services_sales_by_kind_of_business1992_2025.xlsx',
 'motor_fuel_efficiency_mpg.xlsx',
 'pivot_data_example.xlsx',
 'retail_transaction_loyalty_discount_report.xlsx',
 'skilled_worker_employer_sponsorship_list.xlsx',
 'time_series_data.xlsx',
 'uk_constituency_election_result_2019_and_2024.xlsx',
 'uk_election_result_poll.xlsx',
 'uk_house_of_commons_general_election_2024_results_by_constituency.xlsx',
 'uk_smoking_data.csv']

In [12]:
data = load('sundry_data_sources', 'uk_smoking_data.csv')
data.head()

,gender,age,marital_status,highest_qualification,nationality,ethnicity,gross_income,region,smoke,amt_weekends,amt_weekdays,type
0,Male,38,Divorced,No Qualification,British,White,"2,600 to 5,200",The North,No,NaN,NaN,NaN
1,Female,42,Single,No Qualification,British,White,"Under 2,600",The North,Yes,12.0,12.0,Packets
2,Male,40,Married,Degree,English,White,"28,600 to 36,400",The North,No,NaN,NaN,NaN
3,Female,40,Married,Degree,English,White,"10,400 to 15,600",The North,No,NaN,NaN,NaN
4,Female,39,Married,GCSE/O Level,British,White,"2,600 to 5,200",The North,No,NaN,NaN,NaN

In [13]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1691 entries, 0 to 1690
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   gender                 1691 non-null   str
 1   age                    1691 non-null   int64
 2   marital_status         1691 non-null   str
 3   highest_qualification  1691 non-null   str
 4   nationality            1691 non-null   str
 5   ethnicity              1691 non-null   str
 6   gross_income           1691 non-null   str
 7   region                 1691 non-null   str
 8   smoke                  1691 non-null   str
 9   amt_weekends           421 non-null    float64
 10  amt_weekdays           421 non-null    float64
 11  type                   421 non-null    str
dtypes: float64(2), int64(1), str(9)
memory usage: 269.9 KB

In [19]:
data[data['age'].between(20, 30)].max() # Checks if age is between 20 and 30

gender                               Male
age                                    30
marital_status                    Widowed
highest_qualification    Other/Sub Degree
nationality                         Welsh
ethnicity                           White
gross_income                  Under 2,600
region                              Wales
smoke                                 Yes
amt_weekends                         40.0
amt_weekdays                         30.0
type                              Packets
dtype: object