## 4. Pandas Series: Statistical Summary

In [1]:
import pandas as pd
import numpy as np
import fda_toolkit as fda
from onedrive_loader import files, load

In [2]:
files()

['financial_transactions_dataset_analytics_kaggle',
 'powerbI_data_lakehouse',
 'region_electric_hourly_time_series',
 'sundry_data_sources']

In [3]:
dataset = 'sundry_data_sources'
files(dataset)

['22025_qs_world_university_rankings.csv',
 'adidas_us_sales_datasets.xlsx',
 'apple_amazon_google_microsoft_daily_stock_returns_10years.xlsx',
 'country_economy_indicator_1950_2022.xlsx',
 'country_gdp_per_capital_1952_2007.xlsx',
 'end_of_month_retail_inventories_and_inventories1992_2024.xlsx',
 'financial_sample_data.xlsx',
 'job_roles_opening_analyst.xlsx',
 'monthly_retail_and_food_services_sales_by_kind_of_business1992_2025.xlsx',
 'motor_fuel_efficiency_mpg.xlsx',
 'pivot_data_example.xlsx',
 'retail_transaction_loyalty_discount_report.xlsx',
 'sales.csv',
 'skilled_worker_employer_sponsorship_list.xlsx',
 'time_series_data.xlsx',
 'uk_constituency_election_result_2019_and_2024.xlsx',
 'uk_election_result_poll.xlsx',
 'uk_house_of_commons_general_election_2024_results_by_constituency.xlsx',
 'uk_smoking_data.csv']

In [57]:
df = load(dataset,'adidas_us_sales_datasets.xlsx')
df

,Retailer,Retailer ID,Invoice Date,Region,State,City,Product,Price per Unit,Units Sold,Total Sales,Operating Profit,Operating Margin,Sales Method
0,Foot Locker,1185732,2020-01-01,Northeast,New York,New York,Men's Street Footwear,50.0,1200,600000.0,300000.00,0.50,In-store
1,Foot Locker,1185732,2020-01-02,Northeast,New York,New York,Men's Athletic Footwear,50.0,1000,500000.0,150000.00,0.30,In-store
2,Foot Locker,1185732,2020-01-03,Northeast,New York,New York,Women's Street Footwear,40.0,1000,400000.0,140000.00,0.35,In-store
3,Foot Locker,1185732,2020-01-04,Northeast,New York,New York,Women's Athletic Footwear,45.0,850,382500.0,133875.00,0.35,In-store
4,Foot Locker,1185732,2020-01-05,Northeast,New York,New York,Men's Apparel,60.0,900,540000.0,162000.00,0.30,In-store
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9643,Foot Locker,1185732,2021-01-24,Northeast,New Hampshire,Manchester,Men's Apparel,50.0,64,3200.0,896.00,0.28,Outlet
9644,Foot Locker,1185732,2021-01-24,Northeast,New Hampshire,Manchester,Women's Apparel,41.0,105,4305.0,1377.60,0.32,Outlet
9645,Foot Locker,1185732,2021-02-22,Northeast,New Hampshire,Manchester,Men's Street Footwear,41.0,184,7544.0,2791.28,0.37,Outlet
9646,Foot Locker,1185732,2021-02-22,Northeast,New Hampshire,Manchester,Men's Athletic Footwear,42.0,70,2940.0,1234.80,0.42,Outlet
9647,Foot Locker,1185732,2021-02-22,Northeast,New Hampshire,Manchester,Women's Street Footwear,29.0,83,2407.0,649.89,0.27,Outlet

In [59]:
from fda_toolkit import core

In [60]:
df = core.clean_column_headers(df)
df.head()

,retailer,retailer_id,invoice_date,region,state,city,product,price_per_unit,units_sold,total_sales,operating_profit,operating_margin,sales_method
0,Foot Locker,1185732,2020-01-01,Northeast,New York,New York,Men's Street Footwear,50.0,1200,600000.0,300000.0,0.50,In-store
1,Foot Locker,1185732,2020-01-02,Northeast,New York,New York,Men's Athletic Footwear,50.0,1000,500000.0,150000.0,0.30,In-store
2,Foot Locker,1185732,2020-01-03,Northeast,New York,New York,Women's Street Footwear,40.0,1000,400000.0,140000.0,0.35,In-store
3,Foot Locker,1185732,2020-01-04,Northeast,New York,New York,Women's Athletic Footwear,45.0,850,382500.0,133875.0,0.35,In-store
4,Foot Locker,1185732,2020-01-05,Northeast,New York,New York,Men's Apparel,60.0,900,540000.0,162000.0,0.30,In-store

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9648 entries, 0 to 9647
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Retailer          9648 non-null   str
 1   Retailer ID       9648 non-null   int64
 2   Invoice Date      9648 non-null   datetime64[us]
 3   Region            9648 non-null   str
 4   State             9648 non-null   str
 5   City              9648 non-null   str
 6   Product           9648 non-null   str
 7   Price per Unit    9648 non-null   float64
 8   Units Sold        9648 non-null   int64
 9   Total Sales       9648 non-null   float64
 10  Operating Profit  9648 non-null   float64
 11  Operating Margin  9648 non-null   float64
 12  Sales Method      9648 non-null   str
dtypes: datetime64[us](1), float64(4), int64(2), str(6)
memory usage: 1.5 MB

In [29]:
def change_column_header(df):
    df.columns = df.columns.str.strip()
    df.columns = df.columns.str.lower()
    df.columns = df.columns.str.replace(' ', '_')
    return df

# apply the function 
df = change_column_header(df)

In [30]:
df

,retailer,retailer_id,invoice_date,region,state,city,product,price_per_unit,units_sold,total_sales,operating_profit,operating_margin,sales_method
0,Foot Locker,1185732,2020-01-01,Northeast,New York,New York,Men's Street Footwear,50.0,1200,600000.0,300000.00,0.50,In-store
1,Foot Locker,1185732,2020-01-02,Northeast,New York,New York,Men's Athletic Footwear,50.0,1000,500000.0,150000.00,0.30,In-store
2,Foot Locker,1185732,2020-01-03,Northeast,New York,New York,Women's Street Footwear,40.0,1000,400000.0,140000.00,0.35,In-store
3,Foot Locker,1185732,2020-01-04,Northeast,New York,New York,Women's Athletic Footwear,45.0,850,382500.0,133875.00,0.35,In-store
4,Foot Locker,1185732,2020-01-05,Northeast,New York,New York,Men's Apparel,60.0,900,540000.0,162000.00,0.30,In-store
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9643,Foot Locker,1185732,2021-01-24,Northeast,New Hampshire,Manchester,Men's Apparel,50.0,64,3200.0,896.00,0.28,Outlet
9644,Foot Locker,1185732,2021-01-24,Northeast,New Hampshire,Manchester,Women's Apparel,41.0,105,4305.0,1377.60,0.32,Outlet
9645,Foot Locker,1185732,2021-02-22,Northeast,New Hampshire,Manchester,Men's Street Footwear,41.0,184,7544.0,2791.28,0.37,Outlet
9646,Foot Locker,1185732,2021-02-22,Northeast,New Hampshire,Manchester,Men's Athletic Footwear,42.0,70,2940.0,1234.80,0.42,Outlet
9647,Foot Locker,1185732,2021-02-22,Northeast,New Hampshire,Manchester,Women's Street Footwear,29.0,83,2407.0,649.89,0.27,Outlet

In [31]:
df.columns.to_list()

['retailer',
 'retailer_id',
 'invoice_date',
 'region',
 'state',
 'city',
 'product',
 'price_per_unit',
 'units_sold',
 'total_sales',
 'operating_profit',
 'operating_margin',
 'sales_method']

In [32]:
df['units_sold'].describe().round(2)

count    9648.00
mean      256.93
std       214.25
min         0.00
25%       106.00
50%       176.00
75%       350.00
max      1275.00
Name: units_sold, dtype: float64

In [34]:
print(df['units_sold'].count(), df['units_sold'].mean().round(2), df['units_sold'].std().round(2))

9648 256.93 214.25

In [36]:
print(df['units_sold'].count())

9648

In [42]:
df

,retailer,retailer_id,invoice_date,region,state,city,product,price_per_unit,units_sold,total_sales,operating_profit,operating_margin,sales_method
0,Foot Locker,1185732,2020-01-01,Northeast,New York,New York,Men's Street Footwear,50.0,1200,600000.0,300000.00,0.50,In-store
1,Foot Locker,1185732,2020-01-02,Northeast,New York,New York,Men's Athletic Footwear,50.0,1000,500000.0,150000.00,0.30,In-store
2,Foot Locker,1185732,2020-01-03,Northeast,New York,New York,Women's Street Footwear,40.0,1000,400000.0,140000.00,0.35,In-store
3,Foot Locker,1185732,2020-01-04,Northeast,New York,New York,Women's Athletic Footwear,45.0,850,382500.0,133875.00,0.35,In-store
4,Foot Locker,1185732,2020-01-05,Northeast,New York,New York,Men's Apparel,60.0,900,540000.0,162000.00,0.30,In-store
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9643,Foot Locker,1185732,2021-01-24,Northeast,New Hampshire,Manchester,Men's Apparel,50.0,64,3200.0,896.00,0.28,Outlet
9644,Foot Locker,1185732,2021-01-24,Northeast,New Hampshire,Manchester,Women's Apparel,41.0,105,4305.0,1377.60,0.32,Outlet
9645,Foot Locker,1185732,2021-02-22,Northeast,New Hampshire,Manchester,Men's Street Footwear,41.0,184,7544.0,2791.28,0.37,Outlet
9646,Foot Locker,1185732,2021-02-22,Northeast,New Hampshire,Manchester,Men's Athletic Footwear,42.0,70,2940.0,1234.80,0.42,Outlet
9647,Foot Locker,1185732,2021-02-22,Northeast,New Hampshire,Manchester,Women's Street Footwear,29.0,83,2407.0,649.89,0.27,Outlet

In [41]:
df.nunique()

retailer               6
retailer_id            4
invoice_date         724
region                 5
state                 50
city                  52
product                6
price_per_unit       146
units_sold           361
total_sales         3512
operating_profit    6510
operating_margin     127
sales_method           3
dtype: int64

In [40]:
print(df.nunique().count())

13

In [47]:
df.city.unique()

<ArrowStringArray>
[      'New York',        'Houston',  'San Francisco',    'Los Angeles',
        'Chicago',         'Dallas',   'Philadelphia',      'Las Vegas',
         'Denver',        'Seattle',          'Miami',    'Minneapolis',
       'Billings',      'Knoxville',          'Omaha',     'Birmingham',
       'Portland',      'Anchorage',       'Honolulu',        'Orlando',
         'Albany',       'Cheyenne',       'Richmond',        'Detroit',
      'St. Louis', 'Salt Lake City',    'New Orleans',          'Boise',
        'Phoenix',    'Albuquerque',        'Atlanta',     'Charleston',
      'Charlotte',       'Columbus',     'Louisville',        'Jackson',
    'Little Rock',  'Oklahoma City',        'Wichita',    'Sioux Falls',
          'Fargo',     'Des Moines',      'Milwaukee',   'Indianapolis',
      'Baltimore',     'Wilmington',         'Newark',       'Hartford',
     'Providence',         'Boston',     'Burlington',     'Manchester']
Length: 52, dtype: str

In [49]:
df.state.unique()

<ArrowStringArray>
[      'New York',          'Texas',     'California',       'Illinois',
   'Pennsylvania',         'Nevada',       'Colorado',     'Washington',
        'Florida',      'Minnesota',        'Montana',      'Tennessee',
       'Nebraska',        'Alabama',          'Maine',         'Alaska',
         'Hawaii',        'Wyoming',       'Virginia',       'Michigan',
       'Missouri',           'Utah',         'Oregon',      'Louisiana',
          'Idaho',        'Arizona',     'New Mexico',        'Georgia',
 'South Carolina', 'North Carolina',           'Ohio',       'Kentucky',
    'Mississippi',       'Arkansas',       'Oklahoma',         'Kansas',
   'South Dakota',   'North Dakota',           'Iowa',      'Wisconsin',
        'Indiana',  'West Virginia',       'Maryland',       'Delaware',
     'New Jersey',    'Connecticut',   'Rhode Island',  'Massachusetts',
        'Vermont',  'New Hampshire']
Length: 50, dtype: str

In [52]:
df.total_sales.to_list()

[600000.0,
 500000.0,
 400000.0,
 382500.0,
 540000.0,
 500000.0,
 625000.0,
 450000.0,
 380000.0,
 371250.0,
 540000.0,
 500000.0,
 610000.0,
 462500.0,
 380000.0,
 360000.0,
 510000.0,
 475000.0,
 600000.0,
 450000.0,
 360000.0,
 371250.0,
 495000.0,
 475000.0,
 732000.0,
 508750.00000000006,
 450000.0,
 425000.0,
 525000.0,
 650000.0,
 750000.0,
 550000.0000000001,
 462500.0,
 450000.0,
 540000.0,
 682500.0,
 765000.0,
 563750.0000000001,
 475000.0,
 450000.0,
 555000.0,
 715000.0,
 750000.0,
 563750.0000000001,
 475000.0,
 462500.0,
 540000.0,
 698750.0,
 720000.0,
 550000.0000000001,
 462500.0,
 450000.0,
 540000.0,
 650000.0,
 568750.0,
 700000.0,
 747500.0,
 536250.0000000001,
 506000.00000000006,
 495000.00000000006,
 568750.0,
 682500.0,
 780000.0,
 550000.0000000001,
 522500.00000000006,
 495000.00000000006,
 585000.0,
 700000.0,
 225000.0,
 315000.0,
 245000.0,
 245000.0,
 220000.0,
 245000.0,
 212500.0,
 297500.0,
 236250.0,
 218750.0,
 200000.0,
 245000.0,
 262500.0,
 350000.0,
 245000.0,
 240000.0,
 225000.0,
 260000.0,
 270000.0,
 360000.0,
 253750.0,
 250000.0,
 236250.0,
 320000.0,
 277500.0,
 370000.0,
 271250.0,
 280000.0,
 270000.0,
 380000.0,
 380000.0,
 427500.0,
 320000.0,
 300000.0,
 292500.0,
 500000.0,
 380000.0,
 427500.0,
 440000.0,
 280000.0,
 315000.0,
 487500.0,
 370000.0,
 416250.0,
 440000.0,
 260000.0,
 292500.0,
 450000.0,
 382500.0,
 382500.0,
 450000.0,
 312500.0,
 281250.0,
 467500.00000000006,
 360000.0,
 360000.0,
 375000.0,
 300000.0,
 258750.0,
 412500.00000000006,
 405000.0,
 405000.0,
 412500.0,
 337500.0,
 292500.0,
 467500.00000000006,
 427500.0,
 427500.0,
 425000.0,
 350000.0,
 292500.0,
 495000.00000000006,
 310000.0,
 387500.0,
 387500.0,
 312500.0,
 316250.00000000006,
 387500.0,
 330000.0,
 362500.0,
 362500.0,
 287500.0,
 275000.00000000006,
 350000.0,
 425000.0,
 420000.0,
 420000.0,
 360000.0,
 325000.0,
 420000.0,
 525000.0,
 438750.0,
 471250.0,
 375000.0,
 341250.0,
 560000.0,
 540000.0,
 487500.0,
 487500.0,
 390000.0,
 357500.0,
 580000.0,
 585000.0,
 536250.0,
 536250.0,
 420000.0,
 373750.0,
 700000.0,
 615000.0,
 568750.0,
 536250.0,
 435000.0,
 503750.0,
 620000.0,
 633750.0,
 647500.0,
 520000.0,
 487500.0,
 562500.0,
 580000.0,
 508750.00000000006,
 555000.0000000001,
 426250.00000000006,
 398750.00000000006,
 471250.0,
 542500.0,
 481250.00000000006,
 525000.0000000001,
 385000.00000000006,
 371250.00000000006,
 422500.0,
 490000.0,
 481250.00000000006,
 525000.0000000001,
 398750.00000000006,
 385000.00000000006,
 422500.0,
 542500.0,
 536250.0000000001,
 585000.0000000001,
 426250.00000000006,
 426250.00000000006,
 455000.0,
 560000.0,
 245000.0,
 315000.0,
 315000.0,
 247500.0,
 250000.0,
 315000.0,
 262500.0,
 292500.0,
 303750.0,
 236250.0,
 225000.0,
 292500.0,
 280000.0,
 292500.0,
 292500.0,
 247500.0,
 212500.0,
 281250.0,
 360000.0,
 300000.0,
 312500.0,
 236250.0,
 212500.0,
 390000.0,
 360000.0,
 325000.0,
 325000.0,
 247500.0,
 225000.0,
 406250.0,
 405000.0,
 375000.0,
 375000.0,
 281250.0,
 250000.0,
 520000.0,
 427500.0,
 400000.0,
 375000.0,
 292500.0,
 350000.0,
 455000.0,
 450000.0,
 467500.00000000006,
 362500.0,
 337500.0,
 405000.0,
 422500.0,
 425000.0,
 467500.00000000006,
 350000.0,
 325000.0,
 390000.0,
 455000.0,
 400000.0,
 440000.00000000006,
 325000.0,
 312500.0,
 360000.0,
 422500.0,
 412500.0,
 453750.00000000006,
 337500.0,
 325000.0,
 360000.0,
 455000.0,
 450000.0,
 495000.00000000006,
 350000.0,
 350000.0,
 375000.0,
 471250.0,
 213750.0,
 123750.0,
 96250.0,
 50000.0,
 96249.99999999999,
 123750.0,
 236250.0,
 78750.0,
 78750.0,
 40000.0,
 96249.99999999999,
 123750.0,
 247500.0,
 100000.0,
 90000.0,
 33750.0,
 75000.0,
 112500.0,
 225000.0,
 75000.0,
 60000.0,
 33750.0,
 60000.0,
 112500.0,
 297000.0,
 110000.00000000001,
 87500.0,
 50000.0,
 75000.0,
 162500.0,
 250000.0,
 112500.00000000001,
 80000.0,
 70000.0,
 87500.0,
 192500.00000000003,
 287500.0,
 146250.00000000003,
 100000.0,
 80000.0,
 112500.0,
 220000.00000000003,
 275000.0,
 146250.00000000003,
 100000.0,
 90000.0,
 100000.0,
 206250.00000000003,
 250000.0,
 135000.00000000003,
 80000.0,
 70000.0,
 87500.0,
 137500.00000000003,
 255000.0,
 125000.0,
 75000.0,
 62500.0,
 75000.0,
 162499.99999999997,
 240000.0,
 125000.0,
 97500.0,
 87500.0,
 90000.0,
 162499.99999999997,
 300000.0,
 150000.0,
 125000.0,
 100000.0,
 120000.0,
 194999.99999999997,
 145000.0,
 217500.0,
 157500.0,
 183750.0,
 150000.0,
 183750.0,
 168750.0,
 227500.0,
 166250.0,
 148750.0,
 120000.0,
 175000.0,
 202500.0,
 270000.0,
 150000.0,
 140000.0,
 120000.0,
 157500.0,
 140000.0,
 210000.00000000003,
 131249.99999999997,
 127500.00000000001,
 113750.0,
 180000.00000000003,
 150000.0,
 232500.00000000003,
 156249.99999999997,
 192500.0,
 225000.0,
 360000.0,
 360000.0,
 400000.0,
 292500.0,
 270000.0,
 250000.0,
 481250.00000000006,
 371250.0,
 412500.0,
 438750.0,
 258750.0,
 287500.0,
 510000.0,
 400000.0,
 440000.00000000006,
 487500.0,
 262500.0,
 288750.00000000006,
 465000.0,
 398750.00000000006,
 371250.00000000006,
 435000.0,
 270000.0,
 247500.00000000003,
 337500.0,
 250000.0,
 250000.0,
 258750.0,
 191250.0,
 160000.0,
 287500.0,
 290000.0,
 290000.0,
 422500.0,
 325000.0,
 285000.0,
 472500.0,
 495000.0,
 495000.0,
 471250.0,
 373750.0,
 315000.0,
 542500.0,
 191250.0,
 101250.0,
 78750.0,
 30000.0,
 68749.99999999999,
 101250.0,
 213750.0,
 56250.0,
 61250.0,
 20000.0,
 68749.99999999999,
 101250.0,
 222500.0,
 75000.0,
 70000.0,
 11250.0,
 45000.0,
 87500.0,
 225000.0,
 75000.0,
 60000.0,
 33750.0,
 45000.0,
 100000.0,
 282000.0,
 105000.00000000001,
 82500.00000000001,
 55000.00000000001,
 81250.0,
 175000.0,
 325000.0,
 150000.00000000003,
 96250.00000000001,
 82500.00000000001,
 97500.0,
 210000.0,
 325000.0,
 180000.00000000003,
 123750.00000000001,
 96250.00000000001,
 130000.0,
 262500.0,
 341250.0,
 180000.00000000003,
 123750.00000000001,
 110000.00000000001,
 113750.0,
 245000.0,
 308750.0,
 137500.0,
 90000.0,
 78750.0,
 68749.99999999999,
 135000.0,
 240000.0,
 112500.0,
 62500.0,
 50000.0,
 60000.0,
 146249.99999999997,
 262500.0,
 120000.00000000001,
 117000.00000000001,
 105000.00000000001,
 105000.0,
 187500.0,
 332500.0,
 165000.00000000003,
 135000.00000000003,
 105000.00000000001,
 122500.0,
 206250.0,
 157500.0,
 202500.0,
 202500.0,
 135000.0,
 125000.0,
 213750.0,
 183750.0,
 191250.0,
 191250.0,
 123750.0,
 100000.0,
 180000.0,
 247500.0,
 219999.99999999997,
 219999.99999999997,
 164999.99999999997,
 105000.0,
 206249.99999999997,
 330000.0,
 227500.0,
 260000.0,
 180000.0,
 130000.0,
 280000.0,
 330000.0,
 260000.0,
 260000.0,
 180000.0,
 130000.0,
 360000.0,
 420000.0,
 357500.0,
 357500.0,
 255000.0,
 195000.0,
 480000.0,
 450000.0,
 390000.0,
 357500.0,
 270000.0,
 325000.0,
 400000.0,
 455000.0,
 455000.0,
 341250.0,
 308750.0,
 356250.0,
 320000.0,
 360000.00000000006,
 390000.00000000006,
 270000.00000000006,
 240000.00000000003,
 280000.0,
 337500.00000000006,
 330000.00000000006,
 357500.00000000006,
 225000.00000000003,
 210000.00000000003,
 227500.0,
 281250.00000000006,
 345000.00000000006,
 373750.00000000006,
 255000.00000000003,
 240000.00000000003,
 245000.0,
 356250.00000000006,
 405000.00000000006,
 438750.0000000001,
 285000.00000000006,
 285000.00000000006,
 280000.0,
 375000.00000000006,
 127500.0,
 170000.0,
 170000.0,
 110000.0,
 101250.0,
 190000.0,
 157500.0,
 170000.0,
 170000.0,
 110000.0,
 90000.0,
 160000.0,
 220000.0,
 199999.99999999997,
 219999.99999999997,
 164999.99999999997,
 90000.0,
 192499.99999999997,
 315000.0,
 211250.0,
 243750.0,
 165000.0,
 113750.0,
 260000.0,
 315000.0,
 243750.0,
 243750.0,
 165000.0,
 113750.0,
 380000.0,
 435000.0,
 373750.0,
 373750.0,
 292500.0,
 227500.0,
 531250.0000000001,
 503750.0,
 437500.0,
 402500.0,
 308750.0,
 367500.0,
 446250.00000000006,
 507500.0,
 506250.0000000001,
 385000.0,
 350000.0,
 375000.0,
 320000.0,
 390000.00000000006,
 420000.00000000006,
 292500.00000000006,
 260000.00000000006,
 300000.00000000006,
 297500.0,
 288750.00000000006,
 315000.00000000006,
 192500.00000000003,
 178750.00000000003,
 195000.0,
 245000.0,
 316250.00000000006,
 345000.00000000006,
 233750.00000000003,
 260000.00000000006,
 281250.00000000006,
 400000.00000000006,
 455000.0000000001,
 490000.0000000001,
 325000.00000000006,
 325000.00000000006,
 318750.00000000006,
 420000.00000000006,
 180000.0,
 225000.0,
 225000.0,
 150000.0,
 137500.00000000003,
 250000.0,
 220000.0,
 225000.0,
 225000.0,
 150000.0,
 123750.00000000001,
 212500.0,
 287500.0,
 255000.0,
 276249.99999999994,
 211249.99999999994,
 122500.0,
 243749.99999999994,
 385000.0,
 262500.0,
 300000.0,
 180000.0,
 130000.0,
 280000.0,
 330000.0,
 260000.0,
 260000.0,
 180000.0,
 130000.0,
 400000.0,
 562500.0,
 500000.0,
 500000.0,
 400000.0,
 318750.00000000006,
 675000.0,
 660000.0,
 573750.0000000001,
 531250.0000000001,
 420000.0,
 488750.00000000006,
 575000.0,
 658750.0000000001,
 600000.0000000001,
 468750.0000000001,
 431250.00000000006,
 431250.0,
 320000.0,
 420000.00000000006,
 450000.0000000002,
 315000.00000000006,
 280000.00000000006,
 340000.00000000006,
 292500.0,
 330000.00000000006,
 357500.00000000006,
 225000.00000000003,
 210000.00000000003,
 227500.0,
 281250.00000000006,
 360000.00000000006,
 406250.0000000001,
 285000.00000000006,
 315000.00000000006,
 382500.00000000006,
 522500.00000000006,
 600000.0000000001,
 637500.0000000001,
 440000.00000000006,
 440000.00000000006,
 427500.00000000006,
 546250.0000000001,
 472500.0,
 382500.0,
 297500.0,
 280000.0,
 412500.00000000006,
 382500.0,
 495000.0,
 337500.0,
 280000.0,
 270000.0,
 412500.00000000006,
 382500.0,
 481500.0,
 337500.0,
 271250.0,
 250000.0,
 371250.00000000006,
 348750.0,
 461250.0,
 326250.0,
 253750.0,
 260000.0,
 371250.00000000006,
 360000.0,
 588500.0000000001,
 426250.00000000006,
 375000.0,
 350000.0,
 435000.0,
 536250.0,
 645000.0,
 453750.00000000006,
 400000.0,
 387500.0,
 503750.0,
 647500.0,
 747500.0,
 540000.0000000001,
 453750.00000000006,
 426250.00000000006,
 520000.0,
 682500.0,
 731250.0,
 540000.0000000001,
 453750.00000000006,
 348750.0,
 412500.00000000006,
 555000.0000000001,
 577500.0000000001,
 425000.0000000001,
 337500.0,
 326250.0,
 398750.00000000006,
 495000.00000000006,
 600000.0000000001,
 412500.0000000001,
 362500.0000000001,
 350000.0000000001,
 420000.00000000006,
 536250.0,
 585000.0000000001,
 400000.0000000001,
 372500.0000000001,
 387500.0000000001,
 487500.0,
 595000.0,
 698750.0,
 481250.00000000006,
 453750.00000000006,
 426250.00000000006,
 503750.0,
 612500.0,
 157500.0,
 87500.0,
 62500.0,
 30000.000000000004,
 67499.99999999999,
 87500.0,
 175000.0,
 52500.0,
 50000.0,
 22500.000000000004,
 67499.99999999999,
 78750.0,
 178000.0,
 50000.0,
 52500.00000000001,
 8750.0,
 37500.0,
 70000.0,
 160000.0,
 40000.0,
 30000.000000000004,
 8750.0,
 25000.0,
 70000.0,
 222500.0,
 67500.00000000001,
 50000.0,
 20000.0,
 41249.99999999999,
 105000.0,
 191250.0,
 70000.00000000001,
 61250.0,
 52500.0,
 75000.0,
 178750.00000000003,
 275000.0,
 135000.00000000003,
 90000.0,
 70000.0,
 100000.0,
 206250.00000000003,
 262500.0,
 135000.00000000003,
 90000.0,
 61250.0,
 67500.0,
 162500.0,
 202500.0,
 100000.00000000001,
 37500.0,
 31250.0,
 43750.0,
 80000.0,
 168749.99999999997,
 70000.0,
 35000.0,
 26250.0,
 33749.99999999999,
 99999.99999999997,
 175000.0,
 80000.0,
 58000.0,
 60000.0,
 68749.99999999999,
 134999.99999999997,
 261249.99999999997,
 123750.0,
 101250.0,
 78750.0,
 96249.99999999999,
 164999.99999999997,
 166250.0,
 213750.0,
 213750.0,
 146250.0,
 137500.0,
 213750.0,
 183750.0,
 191250.0,
 202500.0,
 135000.0,
 112500.0,
 191250.0,
 201250.0,
 191250.0,
 191250.0,
 146250.0,
 100000.0,
 180000.0,
 258750.0,
 168750.0,
 180000.0,
 120000.0,
 90000.0,
 225000.0,
 230000.0,
 191250.0,
 191250.0,
 130000.0,
 101250.0,
 240000.0,
 270000.0,
 236250.0,
 247500.0,
 170000.0,
 135000.0,
 360000.0,
 300000.0,
 270000.0,
 247500.0,
 180000.0,
 213750.0,
 285000.0,
 303750.0,
 343750.00000000006,
 250000.0,
 191250.0,
 233749.99999999997,
 240000.0,
 270000.0,
 300000.0,
 202500.0,
 180000.0,
 219999.99999999997,
 270000.0,
 247500.0,
 275000.0,
 180000.0,
 168750.0,
 192499.99999999997,
 240000.0,
 230000.0,
 258750.00000000003,
 170000.0,
 170000.0,
 206249.99999999997,
 285000.0,
 303750.0,
 337500.0,
 213750.0,
 213750.0,
 219999.99999999997,
 300000.0,
 140000.0,
 210000.0,
 150000.0,
 175000.0,
 140000.0,
 175000.0,
 162500.0,
 218750.0,
 157500.0,
 140000.0,
 110000.0,
 166250.0,
 195000.0,
 260000.0,
 142500.0,
 131250.0,
 110000.0,
 148750.0,
 135000.0,
 168750.00000000006,
 99999.99999999999,
 100000.00000000003,
 90000.0,
 143750.00000000003,
 108749.99999999997,
 187500.00000000006,
 119999.99999999999,
 157500.00000000003,
 191250.0,
 310000.0,
 310000.0,
 348750.0,
 260000.0,
 240000.0,
 225000.0,
 437500.0,
 330000.0,
 371250.0,
 390000.0,
 230000.0,
 247500.0,
 453749.99999999994,
 348750.0,
 426250.00000000006,
 475000.0,
 213750.0,
 237500.0,
 398749.99999999994,
 337500.0,
 312500.0,
 371249.99999999994,
 219999.99999999997,
 200000.0,
 281250.0,
 201250.0,
 201250.0,
 210000.0,
 150000.0,
 122500.0,
 236250.0,
 202500.00000000003,
 202500.00000000003,
 330000.00000000006,
 261250.00000000003,
 247499.99999999997,
 422500.0,
 439999.99999999994,
 439999.99999999994,
 ...]

In [55]:
print(df.total_sales.idxmax(), df.total_sales.max().round(2))

1394 825000.0